feat: implement jpeg xl codec
tistech0/Pictou pull request #101
Opened 2024-04-02 07:59 UTC by AndreasLrx

Fix default max image size (10_000_000 -> 20_000_000)
And openapi oauth2 urls

2024-04-02 10:26 UTC, BaptistePgn submitted a review, later dismissed

2024-04-02 22:49 UTC, MisterPeModder requested changes
Works pretty well for real life images !

For some reasons, the following image fails to encode properly and takes 4x the storage space when "compressed" (from 143kB to 451kB).

![sbt_banner](https://github.com/tistech0/Pictou/assets/7838479/0ecc1d65-d0aa-42a2-96b5-93f206b303e1)

Also here's a patch to get the build working under Nix:
(apply with `patch shell.nix < thepatch.patch`)
```patch
--- a/shell.nix
+++ b/shell.nix
@@ -1,14 +1,32 @@
 { pkgs ? import <nixpkgs> {} }:

-pkgs.mkShell {
-  name = "pictou";
-  buildInputs = with pkgs; [
-    pre-commit
-    diesel-cli
-    postgresql
-  ];
+let
+  libjxl-0-10-2 = pkgs.libjxl.overrideAttrs (old: {
+    version = "0.10.2";
+    src = pkgs.fetchFromGitHub {
+      owner = "libjxl";
+      repo = "libjxl";
+      rev = "v0.10.2";
+      hash = "sha256-Ip/5fbzt6OfIrHJajnxEe14ppvX1hJ1FSJUBEE/h5YQ=";
+      # There are various submodules in `third_party/`.
+      fetchSubmodules = true;
+    };
+  });
+in
+  pkgs.mkShell {
+    name = "pictou";
+    buildInputs = with pkgs; [
+      pre-commit
+      diesel-cli
+      postgresql
+      libjxl-0-10-2
+    ];

-  shellHook = ''
-    pre-commit install
-  '';
-}
+    nativeBuildInputs = with pkgs; [
+      pkg-config
+    ];
+
+    shellHook = ''
+      pre-commit install
+    '';
+  }
```

2024-04-02 22:49 UTC, MisterPeModder commented on back/Cargo.toml
> +jpegxl-rs = { version = "~0.10.2", features=["image"] }
nit: formatting; should be `features = [ "image" ]`

2024-04-02 22:49 UTC, MisterPeModder commented on back/src/api/images.rs
The algorithm at line [423](https://github.com/tistech0/Pictou/pull/101/files#diff-3e0c03cce2926a64d6ee317f1f2b45a99c3c8c2f386d66b8787815ce8d0674e2R423) should be "jxl" or something.

2024-04-02 22:49 UTC, MisterPeModder commented on README.md
> +
Pkg-config is also needed for the build on Linux. For windows and MacOS I don't know.

2024-04-08 08:27 UTC, MisterPeModder approved these changes

2024-04-08 08:27 UTC, merged