fix: shared album and openapi patch album
tistech0/pictou pull request #131
Opened 2024-04-16 14:14 UTC by BaptistePgn

closes #123

2024-04-16 15:25 UTC, AndreasLrx approved these changes

2024-04-16 16:33 UTC, MisterPeModder requested changes

2024-04-16 16:33 UTC, MisterPeModder commented on back/src/api/albums.rs
> +                insert_into(shared_albums::table)
Be consistent, either use `diesel::delete(), diesel::update(), ...` everywhere ***OR*** use imported functions `delete(), update()`

2024-04-17 20:33 UTC, MisterPeModder approved these changes

2024-04-17 20:33 UTC, merged